const data = {
  categoryProducts: [
    {
      name: 'Benih dan bibit',
      slug: 'benih-dan-bibit',
      image: '/assets/images/category-product/benih.png',
      color: 'tani-grey',
      description: 'benih dan bibit',
    },
    {
      name: 'Alat Pertanian',
      slug: 'alat-pertanian',
      image: '/assets/images/category-product/alat-pertanian.png',
      color: 'tani-grey',
      description: 'alat pertanian',
    },
    {
      name: 'Pupuk',
      slug: 'pupuk',
      image: '/assets/images/category-product/pupuk.png',
      color: 'tani-grey',
      description: 'pupuk',
    },
    {
      name: 'Peralatan Kebun',
      slug: 'peralatan-kebun',
      image: '/assets/images/category-product/peralatan-kebun.png',
      color: 'tani-grey',
      description: 'peralatan kebun',
    },
    {
      name: 'Benih dan bibit',
      slug: 'benih-dan-bibit',
      image: '/assets/images/category-product/benih.png',
      color: 'tani-grey',
      description: 'benih dan bibit',
    },
    {
      name: 'Alat Pertanian',
      slug: 'alat-pertanian',
      image: '/assets/images/category-product/alat-pertanian.png',
      color: 'tani-grey',
      description: 'alat pertanian',
    },
    {
      name: 'Pupuk',
      slug: 'pupuk',
      image: '/assets/images/category-product/pupuk.png',
      color: 'tani-grey',
      description: 'pupuk',
    },
    {
      name: 'Peralatan Kebun',
      slug: 'peralatan-kebun',
      image: '/assets/images/category-product/peralatan-kebun.png',
      color: 'tani-grey',
      description: 'peralatan kebun',
    },
    {
      name: 'Pupuk',
      slug: 'pupuk',
      image: '/assets/images/category-product/pupuk.png',
      color: 'tani-grey',
      description: 'pupuk',
    },
    {
      name: 'Peralatan Kebun',
      slug: 'peralatan-kebun',
      image: '/assets/images/category-product/peralatan-kebun.png',
      color: 'tani-grey',
      description: 'peralatan kebun',
    },
    {
      name: 'Peralatan Kebun',
      slug: 'peralatan-kebun',
      image: '/assets/images/category-product/peralatan-kebun.png',
      color: 'tani-grey',
      description: 'peralatan kebun',
    },
  ],

  product: [
    {
      name: 'Bibit Cabe Rawit Rawita F1 - 350 Biji',
      slug: 'bibit-cabe-rawit',
      category: 'Benih Sayuran',
      image: '/assets/images/product/caberawit.jpg',
      discount: 'Rp. 27.000.-',
      price: 'Rp. 23.000,-',
      description: 'benih dan bibit',
    },
    {
      name: 'Bibit Sawi Hijau',
      slug: 'bibit-sawi-hijau',
      category: 'Benih Sayuran',
      image: '/assets/images/product/sawihijau.jpg',
      discount: 'Rp. 27.000.-',
      price: 'Rp. 23.000,-',
      description: 'benih dan bibit',
    },
    {
      name: 'Pupuk Cair',
      slug: 'pupuk-cair',
      category: 'Pupuk',
      image: '/assets/images/product/pupukcair.jpg',
      discount: 'Rp. 27.000.-',
      price: 'Rp. 23.000,-',
      description: 'benih dan bibit',
    },
    {
      name: 'Bibit Cabe Rawit Rawita F1 - 350 Biji',
      slug: 'bibit-cabe-rawit',
      category: 'Benih Sayuran',
      image: '/assets/images/product/caberawit.jpg',
      discount: 'Rp. 27.000.-',
      price: 'Rp. 23.000,-',
      description: 'benih dan bibit',
    },
    {
      name: 'Bibit Sawi Hijau',
      slug: 'bibit-sawi-hijau',
      category: 'Benih Sayuran',
      image: '/assets/images/product/sawihijau.jpg',
      discount: 'Rp. 27.000.-',
      price: 'Rp. 23.000,-',
      description: 'benih dan bibit',
    },
    {
      name: 'Pupuk Cair',
      slug: 'pupuk-cair',
      category: 'Pupuk',
      image: '/assets/images/product/pupukcair.jpg',
      discount: 'Rp. 27.000.-',
      price: 'Rp. 23.000,-',
      description: 'benih dan bibit',
    },
    {
      name: 'Bibit Cabe Rawit Rawita F1 - 350 Biji',
      slug: 'bibit-cabe-rawit',
      category: 'Benih Sayuran',
      image: '/assets/images/product/caberawit.jpg',
      discount: 'Rp. 27.000.-',
      price: 'Rp. 23.000,-',
      description: 'benih dan bibit',
    },
    {
      name: 'Bibit Sawi Hijau',
      slug: 'bibit-sawi-hijau',
      category: 'Benih Sayuran',
      image: '/assets/images/product/sawihijau.jpg',
      discount: 'Rp. 27.000.-',
      price: 'Rp. 23.000,-',
      description: 'benih dan bibit',
    },
  ],
};

export default data;
